language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ree

# This is to work around the version of bundler installed in Travis and
# https://github.com/bundler/bundler/issues/3558
before_install:
  - gem update bundler
